name: Build

on:
    workflow_dispatch:
    push:
    pull_request:
    merge_group:

permissions:
    contents: read

jobs:
    build_on_linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: 18
                  cache: npm
            - name: install dependencies
              run: npm ci
            - name: build
              run: npm run make

    build_on_mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: 18
                  cache: npm
            - name: install dependencies
              run: npm ci
            - name: build
              run: npm run make

    build_on_win:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: 18
                  cache: npm
            - name: install dependencies
              run: npm ci
            - name: build
              run: npm run make
