name: Validate

on:
  workflow_dispatch:
  push:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest

    name: eslint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci # install dependencies

      - name: Run eslint
        run: npm run lint # run eslint
  prettier:
    runs-on: ubuntu-latest

    name: prettier
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci # install dependencies

      - name: Run prettier
        run: npm run prettier  # run prettier
